version: "3"
services:
  serveur_web:
    image: nginx
    volumes:
      - "../:/app"
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php_fpm
    ports:
      - 8000:80
  php_fpm:
    image: php7.3-fpm-xdebug
    volumes:
      - "../:/app"
      - "./config/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    depends_on:
      - database_service
  database_service:
    image: amd64/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"